# Generated by Django 5.2.1 on 2025-07-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobranza',
            old_name='metodo_pago',
            new_name='tipo_pago',
        ),
    ]
