# Generated by Django 5.2.1 on 2025-07-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0002_rename_metodo_pago_cobranza_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobranza',
            name='motivo_baja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
