# Generated by Django 5.2.1 on 2025-07-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0002_modificacionorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor')], default='proveedor', max_length=20),
        ),
    ]
