# Generated by Django 5.2.1 on 2025-07-06 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ordenes_compra', '0003_ordendecompra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientes'),
        ),
    ]
