# Generated by Django 5.2.1 on 2025-07-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0004_ordendecompra_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
