# Generated by Django 5.2.1 on 2025-07-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('ordenes_compra', '0003_ordendecompra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes_compra.ordendecompra'),
        ),
    ]
